merge dev to main
kFocusing/Currency-Exchange pull request #7
Opened 2022-10-14 01:28 UTC by kFocusing

2022-10-16 11:42 UTC, Nikitax23 requested changes
супер-критичного ничего нет. в целом - нормально. 

но есть очень много моментов, которые можно улучшить. 
а есть, которые необходимо поменять!

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/DataSource/ExchangeDataSource.swift
> +            if let amountCurrency = item as? AmountCurrency {
если у тебя будет 100 вариантов энама, ты будешь писать 100 else if let-ов ??? 
почему не использовать switch здесь?

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Model/DealTypeEnum.swift
> +enum DealTypeEnum: Int, BaseEnumProtocol {
`BaseEnumProtocol`

что значит BaseEnumProtocol? 
что другой разработчик должен понять с этого названия? какая смысловая нагрузка вообще?

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Model/ExchangeModel.swift
> +    var dealType: DealTypeEnum
`DealTypeEnum`

не нужно добавлять в названия энамов слово `Enum`
и так же само в названия протоколов - слово `Protocol`

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +    func convertCurrencyBalanceIfPossible()
`convertCurrencyBalanceIfPossible`
не нужно писать ifPossible .

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +    private var currencyExchange: [ExchangeModel] = []
`currencyExchange`
почему список называется неинформативно? как мне понять, что это список? 

что означает эта проперти? интуитивно не понятно

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +                self?.view?.configureAlert(with: [(Localized.AlertActions.done,
```
self?.view?.configureAlert(with: [(Localized.AlertActions.done,
                                                   UIAlertAction.Style.default,
                                                   { return })],
                                           alertTitle: Localized.ErrorAlert.title,
                                           alertMessage: Localized.ErrorAlert.message(error))
```

ты это всё будешь копипастить каждый раз, когда тебе надо будет прокинуть ошибку из этого презентера? 
или может презентер вообшще ничего не должен об этом знать?
он должен отдать текст ошибки или ошибку, которую получил. и сказать "вью, покажи ошибку". и ему не важно, как там это будет отображаться. в UIAlertController-e (с экшнами , тайтлами, и тд), или в каком-то кастомном попапе. 

Презентеру всё равно на UI.

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +        DispatchQueue.global().asyncAfter(deadline: .now() + 3,
очень долго 3 секунды

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +        DispatchQueue.global().asyncAfter(deadline: .now() + 3,
следует уменьшить до 0.5 - 1 sec

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +                                      and: DealTypeEnum.sell)
`DealTypeEnum.sell`
можно просто .sell 

так же само для receive

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +        exemptionPayingCommission -= 1
здесь я не понимаю, зачем декрементим ?

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +        view?.configureAlert(with: [(Localized.AlertActions.done,
это неправильно, должен этим заниматься ViewController .

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +        view?.configureAlert(with: [(Localized.AlertActions.done,
в него можно только передать нужные параметры, если он принимает какие-то параметры . 

если тебе надо сложить строку, то сложи её. и отдай VC как месседж

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +            currencyExchange[DealTypeEnum.sell.rawValue].amountCurrency.amount = amountFromCurrencyExchange
я бы тут переделал на `first(where: {$0 == .sell})` и тд 

и тогда нет шансов словить краш , обращаясь по индексу к массиву. потому что вернется опционал

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/NetworkService/NetworkService.swift
> +        let decoder = JSONDecoder()
ошибка парсинга должна обрабатываться . луче бы тут ты try catch либо не обрабатывал, и прокинул просто throw 

либо орабатывал, но вернул ошибку отсюда, в случае ошибки парсинга.

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Router/Router.swift
> +
зачем куча этих пробелов? во всех протоколах
они лишние. убери их , пожалуйста

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/Router/Router.swift
> +
вот тебе и одна из причин, почему я против вот этого навигейшн контроллера. 
ПОЧЕМУ ОН У ТЕБЯ ОПЦИОНАЛЬНЫЙ, ЕСЛИ ТЫ ЕГО ПЕРЕДАЁШЬ В ЛЮБОМ СЛУЧАЕ В ИНИТЕ???
и каждый раз разворачиваешь if let -ом его 

это полная ерунда!

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/App&SceneDelegate/SceneDelegate.swift
> +        let assemblyBuilder = AssamblyModelBuilder()
1) я против такой архитектуры.
где роутер принимает navigationController, assembly на входе. 
роутер должен принимать просто уже готовый viewController, у которого проставлены уже все связи. 
и через него всегда можно получить доступ к navigationController-y . Но уже не нужно всё менять, я думаю. 

2) `navigationController.navigationBar.isHidden = true` вот это как что-то из страшного сна. такого априори не должно быть! настройка навигейшн бара всегда происходит внутри того вьюконтроллера или навигейшн контроллера!

2022-10-16 11:42 UTC, Nikitax23 commented on Currency-Exchange/AssemblyModelBuilder/AssemblyModelBuilder.swift
> +        let networkService = NetworkService()
я бы тут сделал ту обёртку в навигейшн, которую ты делаешь в `SceneDelegate`

2022-10-17 09:15 UTC, kFocusing commented on Currency-Exchange/Extensions/CGFloatExtension.swift
> +    static var screenWidth: CGFloat {
done

2022-10-17 09:15 UTC, kFocusing commented on Currency-Exchange/Extensions/CellReusableExtension.swift
> +protocol Reusable { }
done

2022-10-17 09:16 UTC, kFocusing commented on Currency-Exchange/Extensions/UITextFieldExtension.swift
> +    func setCursorLocation(_ location: Int) {
done

2022-10-17 09:16 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Model/DealTypeEnum.swift
> +enum DealTypeEnum: Int, BaseEnumProtocol {
done

2022-10-17 09:16 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Model/ExchangeModel.swift
> +    var dealType: DealTypeEnum
done

2022-10-17 09:16 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +    private var currencyExchange: [ExchangeModel] = []
done

2022-10-17 09:16 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +                self?.view?.configureAlert(with: [(Localized.AlertActions.done,
done

2022-10-17 09:16 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +        DispatchQueue.global().asyncAfter(deadline: .now() + 3,
done

2022-10-17 09:16 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +                                      and: DealTypeEnum.sell)
done

2022-10-17 09:16 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +        exemptionPayingCommission -= 1
по заданию у юзера есть 5 беслпатных попыток, а потом должна сниматься комиссия
соответственно тут и у меньшаем количество бесплатных попыток

2022-10-17 09:17 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +        view?.configureAlert(with: [(Localized.AlertActions.done,
done

2022-10-17 09:17 UTC, kFocusing commented on Currency-Exchange/NetworkService/NetworkService.swift
> +        let decoder = JSONDecoder()
done

2022-10-17 09:18 UTC, kFocusing commented on Currency-Exchange/Router/Router.swift
> +
DONE

2022-10-17 09:18 UTC, kFocusing commented on Currency-Exchange/App&SceneDelegate/SceneDelegate.swift
> +        let assemblyBuilder = AssamblyModelBuilder()
2 done
1 забываю этот подход и больше не использую

2022-10-17 09:18 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +    func convertCurrencyBalanceIfPossible()
done

2022-10-17 09:19 UTC, kFocusing commented on Currency-Exchange/Router/Router.swift
> +
done

2022-10-17 09:24 UTC, kFocusing commented on Currency-Exchange/Modules/Exchange/Presenter/ExchangePresenter.swift
> +            currencyExchange[DealTypeEnum.sell.rawValue].amountCurrency.amount = amountFromCurrencyExchange
мне нравится, но в моем случае не получилось использовать
ибо он возвращает не мутейтабл свойство

2022-10-17 11:52 UTC, closed without merging